# Generated by Django 2.1.5 on 2020-06-06 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_type', models.CharField(max_length=100)),
                ('parent_id', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
