# Generated by Django 2.1.5 on 2020-06-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_type',
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent_id',
            field=models.CharField(max_length=100),
        ),
    ]
