# Generated by Django 2.1.5 on 2020-06-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0004_userprofile_is_super_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fonction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='permissions',
            field=models.CharField(default='', max_length=100),
        ),
    ]
