# Generated by Django 2.1.5 on 2020-06-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0005_auto_20200608_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_super_user',
        ),
    ]
