# Generated by Django 2.1.5 on 2020-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0006_remove_userprofile_is_super_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tel',
            field=models.CharField(default='', max_length=100),
        ),
    ]
