# Generated by Django 2.1.5 on 2020-06-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0008_sportif'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportif',
            name='fiche',
            field=models.FileField(default='', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='sportif',
            name='mail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
