# Generated by Django 2.1.5 on 2020-06-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0009_auto_20200608_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportif',
            name='fiche',
            field=models.TextField(default=''),
        ),
    ]
