# Generated by Django 2.1.5 on 2020-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css', '0010_auto_20200609_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportif',
            name='categorie_id',
        ),
        migrations.RemoveField(
            model_name='sportif',
            name='mail',
        ),
        migrations.AddField(
            model_name='sportif',
            name='dob',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sportif',
            name='nationalite',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sportif',
            name='poste',
            field=models.CharField(default='', max_length=100),
        ),
    ]
